spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/mung
    username: test1
    password: 1234

mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis-config.xml

itemImgLocation: D:/pet/item
uploadPath: file:///D:/pet/

